# Generated by Django 6.0.2 on 2026-04-03 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512)),
                ('tags', models.ManyToManyField(blank=True, related_name='materials', to='core.tag')),
            ],
            options={
                'db_table': 'api_material',
            },
        ),
        migrations.CreateModel(
            name='MaterialVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('divisor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='materials.material')),
                ('source_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxy_variants', to='materials.materialvariant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='core.unit')),
            ],
            options={
                'db_table': 'api_materialvariant',
            },
        ),
        migrations.CreateModel(
            name='RelatedMaterial',
            fields=[
                ('pk', models.CompositePrimaryKey('material1_id', 'material2_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('material1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='materials.material')),
                ('material2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='materials.material')),
            ],
            options={
                'db_table': 'api_relatedmaterial',
            },
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='materials/')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='materials.material')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.store')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='materials.materialvariant')),
            ],
            options={
                'db_table': 'api_materialimage',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('variant__isnull', True)), models.Q(('material__isnull', True), ('variant__isnull', False)), _connector='OR'), name='material_or_variant_not_null')],
            },
        ),
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(blank=True, default='', max_length=255)),
                ('price_from_api', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='core.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='materials.materialvariant')),
            ],
            options={
                'db_table': 'api_priceinfo',
                'constraints': [models.UniqueConstraint(fields=('store', 'variant'), name='unique_store_variant_price')],
            },
        ),
    ]
